import { Track, Playlist } from '@/types'

export const mockTracks: Track[] = [
  {
    id: '1',
    title: 'Deep Sleep Healing 432Hz',
    description: 'Fall into deep, restful sleep with healing frequencies',
    category: 'sleep',
    source: 'youtube',
    youtubeUrl: 'https://www.youtube.com/watch?v=t0jwkCd-0Uk',
    thumbnailUrl: 'https://i.ytimg.com/vi/t0jwkCd-0Uk/maxresdefault.jpg',
    duration: 3600,
    creatorId: 'user1',
    creatorName: 'Healing Vibes',
    plays: 125000,
    likes: 8500,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Wealth & Abundance Manifestation',
    description: 'Attract wealth and prosperity into your life',
    category: 'wealth',
    source: 'youtube',
    youtubeUrl: 'https://www.youtube.com/watch?v=example2',
    thumbnailUrl: '',
    duration: 2400,
    creatorId: 'user2',
    creatorName: 'Manifest Master',
    plays: 89000,
    likes: 6200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Confidence Booster - Self Love',
    description: 'Build unshakeable confidence and self-love',
    category: 'confidence',
    source: 'youtube',
    youtubeUrl: 'https://www.youtube.com/watch?v=example3',
    thumbnailUrl: '',
    duration: 1800,
    creatorId: 'user3',
    creatorName: 'Power Within',
    plays: 67000,
    likes: 4800,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Focus & Productivity 40Hz Gamma',
    description: 'Enhance focus and cognitive performance',
    category: 'focus',
    source: 'youtube',
    youtubeUrl: 'https://www.youtube.com/watch?v=example4',
    thumbnailUrl: '',
    duration: 3000,
    creatorId: 'user1',
    creatorName: 'Brain Boost',
    plays: 112000,
    likes: 7300,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Anxiety Relief - Calm Mind',
    description: 'Release anxiety and find inner peace',
    category: 'anxiety',
    source: 'youtube',
    youtubeUrl: 'https://www.youtube.com/watch?v=example5',
    thumbnailUrl: '',
    duration: 2700,
    creatorId: 'user2',
    creatorName: 'Peaceful Mind',
    plays: 143000,
    likes: 9100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Deep Healing Meditation 528Hz',
    description: 'DNA repair and deep healing frequencies',
    category: 'healing',
    source: 'youtube',
    youtubeUrl: 'https://www.youtube.com/watch?v=example6',
    thumbnailUrl: '',
    duration: 4200,
    creatorId: 'user3',
    creatorName: 'Healing Vibes',
    plays: 98000,
    likes: 6700,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockPlaylists: Playlist[] = [
  {
    id: 'p1',
    name: 'Morning Motivation',
    description: 'Start your day with powerful energy',
    coverImage: '',
    tracks: mockTracks.slice(0, 3),
    creatorId: 'user1',
    creatorName: 'Admin',
    isPublic: true,
    likes: 12000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p2',
    name: 'Night Time Healing',
    description: 'Relax and heal while you sleep',
    coverImage: '',
    tracks: mockTracks.slice(3, 6),
    creatorId: 'user1',
    creatorName: 'Admin',
    isPublic: true,
    likes: 8500,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
